#!/usr/bin/env node
/**
 * 인터랙티브 시크릿 설정 스크립트.
 *  - 비밀번호를 물어보고 bcrypt 해시 생성
 *  - JWT_SIGNING_SECRET, BACKEND_SHARED_SECRET 자동 생성
 *  - .env.local 파일을 작성 (로컬 개발용)
 *  - Vercel CLI가 있으면 `vercel env add ... production` 자동 실행
 *  - 백엔드와 공유할 BACKEND_SHARED_SECRET을 마지막에 한 번만 표시
 */
import bcrypt from 'bcryptjs';
import crypto from 'node:crypto';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { spawn, spawnSync } from 'node:child_process';
import { createInterface } from 'node:readline';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const ENV_PATH = join(ROOT, '.env.local');

const colors = {
  reset: '\x1b[0m',
  bold: '\x1b[1m',
  dim: '\x1b[2m',
  red: '\x1b[31m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  cyan: '\x1b[36m',
};

function print(msg) {
  process.stdout.write(msg + '\n');
}

function ask(question) {
  return new Promise((resolve) => {
    const rl = createInterface({ input: process.stdin, output: process.stdout });
    rl.question(question, (a) => {
      rl.close();
      resolve(a.trim());
    });
  });
}

function askHidden(question) {
  return new Promise((resolve) => {
    const stdin = process.stdin;
    process.stdout.write(question);
    const wasRaw = stdin.isRaw;
    stdin.setRawMode?.(true);
    stdin.resume();
    stdin.setEncoding('utf8');
    let value = '';
    const onData = (ch) => {
      const c = String(ch);
      const code = c.charCodeAt(0);
      if (code === 13 || code === 10) {
        stdin.removeListener('data', onData);
        stdin.setRawMode?.(wasRaw ?? false);
        stdin.pause();
        process.stdout.write('\n');
        resolve(value);
      } else if (code === 3) {
        process.stdout.write('\n');
        process.exit(130);
      } else if (code === 8 || code === 127) {
        if (value.length > 0) {
          value = value.slice(0, -1);
          process.stdout.write('\b \b');
        }
      } else if (code >= 32) {
        value += c;
        process.stdout.write('*');
      }
    };
    stdin.on('data', onData);
  });
}

function randomHex(bytes) {
  return crypto.randomBytes(bytes).toString('hex');
}

function hasVercelCli() {
  const r = spawnSync('vercel', ['--version'], { stdio: 'ignore' });
  return r.status === 0;
}

function runVercelEnv(name, value, env) {
  return new Promise((resolve, reject) => {
    const child = spawn('vercel', ['env', 'add', name, env], {
      cwd: ROOT,
      stdio: ['pipe', 'inherit', 'inherit'],
    });
    child.stdin.write(value + '\n');
    child.stdin.end();
    child.on('exit', (code) => {
      if (code === 0) resolve();
      else reject(new Error(`vercel env add ${name} 실패 (exit ${code})`));
    });
  });
}

function parseEnvFile(content) {
  const out = {};
  for (const raw of content.split(/\r?\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq === -1) continue;
    out[line.slice(0, eq).trim()] = line.slice(eq + 1).trim();
  }
  return out;
}

function writeEnvFile(values) {
  const lines = [
    '# Auto-generated by scripts/setup-secrets.mjs',
    '# DO NOT COMMIT this file.',
    '',
  ];
  for (const [k, v] of Object.entries(values)) {
    lines.push(`${k}=${v}`);
  }
  writeFileSync(ENV_PATH, lines.join('\n') + '\n', { mode: 0o600 });
}

function printManualCommands(values) {
  print('');
  print(`${colors.bold}수동 등록 명령어:${colors.reset}`);
  for (const k of Object.keys(values)) {
    print(`  vercel env add ${k} production`);
  }
  print(`  ${colors.dim}(각 명령 실행 시 .env.local의 값을 붙여넣으세요)${colors.reset}`);
}

async function main() {
  print(`${colors.bold}${colors.cyan}김과외 어드민 - 시크릿 설정${colors.reset}`);
  print(`${colors.dim}.env.local 자동 생성 + Vercel production env 등록${colors.reset}`);
  print('');

  let password = '';
  while (true) {
    const a = await askHidden('새 어드민 비밀번호 (8자 이상): ');
    if (a.length < 8) {
      print(`${colors.red}8자 이상이어야 합니다.${colors.reset}`);
      continue;
    }
    const b = await askHidden('한 번 더 입력: ');
    if (a !== b) {
      print(`${colors.red}일치하지 않습니다. 다시 시도해주세요.${colors.reset}`);
      continue;
    }
    password = a;
    break;
  }

  const defaultBackend =
    'https://dev-admin-api-cycndteybqbvbzc4.koreacentral-01.azurewebsites.net';
  print('');
  print(`${colors.dim}백엔드 API URL — 알림톡/푸시 발송을 실제로 처리하는 Azure 서버 주소.${colors.reset}`);
  print(`${colors.dim}기본값: ${defaultBackend}${colors.reset}`);
  const backendInput = await ask(`백엔드 URL (Enter = 기본값 그대로): `);
  const azureBase = backendInput || defaultBackend;

  print('');
  print(`${colors.dim}production 도메인 — Vercel이 발급한 사이트 주소.${colors.reset}`);
  print(`${colors.dim}Vercel 대시보드 → 프로젝트 → Domains에서 확인. 모르면 Enter 눌러 나중에 수정 가능.${colors.reset}`);
  print(`${colors.dim}반드시 https:// 포함 (끝에 슬래시 없이).${colors.reset}`);
  let allowedOrigin = 'http://localhost:5173';
  while (true) {
    const input = await ask(
      'production 도메인 (Enter = http://localhost:5173): ',
    );
    if (!input) break;
    let normalized = input.trim();
    if (!/^https?:\/\//.test(normalized)) {
      normalized = 'https://' + normalized;
      print(`${colors.yellow}→ https:// 자동 추가: ${normalized}${colors.reset}`);
    }
    normalized = normalized.replace(/\/$/, '');
    try {
      new URL(normalized);
      allowedOrigin = normalized;
      break;
    } catch {
      print(`${colors.red}올바른 URL 형식이 아닙니다. 다시 입력해주세요.${colors.reset}`);
    }
  }

  let pwVersion = 1;
  if (existsSync(ENV_PATH)) {
    const existing = parseEnvFile(readFileSync(ENV_PATH, 'utf8'));
    const cur = parseInt(existing.PW_VERSION ?? '0', 10);
    if (Number.isFinite(cur) && cur >= 1) pwVersion = cur + 1;
  }

  print('');
  print('시크릿 생성 중...');
  const pwHash = await bcrypt.hash(password, 12);
  const jwtSecret = randomHex(32);
  const backendSecret = randomHex(32);

  const values = {
    ADMIN_PW_HASH: pwHash,
    PW_VERSION: String(pwVersion),
    JWT_SIGNING_SECRET: jwtSecret,
    BACKEND_SHARED_SECRET: backendSecret,
    AZURE_API_BASE: azureBase,
    SESSION_COOKIE_NAME: 'ka_admin_sid',
    ALLOWED_ORIGIN: allowedOrigin,
  };
  writeEnvFile(values);
  print(`${colors.green}OK .env.local 작성 완료${colors.reset}`);

  const useVercel = hasVercelCli();
  if (useVercel) {
    const answer = await ask(
      `\nVercel CLI 감지됨. production env에 자동 등록할까요? [Y/n]: `,
    );
    if (answer.toLowerCase() !== 'n') {
      print('');
      print('Vercel production env 업데이트 중...');
      try {
        for (const [k, v] of Object.entries(values)) {
          print(`  - ${k}`);
          await runVercelEnv(k, v, 'production');
        }
        print(`${colors.green}OK Vercel env 등록 완료${colors.reset}`);
        print(`${colors.dim}  같은 이름의 기존 env가 있어 실패한 경우, Vercel 대시보드에서 삭제 후 재실행하세요.${colors.reset}`);
      } catch (e) {
        print(`${colors.yellow}일부 실패: ${e.message}${colors.reset}`);
        printManualCommands(values);
      }
    } else {
      printManualCommands(values);
    }
  } else {
    print('');
    print(`${colors.yellow}Vercel CLI 미설치.${colors.reset} 아래 두 가지 중 하나로 production env를 등록하세요.`);
    print('');
    print(`${colors.bold}옵션 A) Vercel 대시보드에서 직접 입력:${colors.reset}`);
    print('  Settings > Environment Variables > 아래 키/값을 Production scope로 추가');
    for (const [k, v] of Object.entries(values)) {
      const preview = v.length > 24 ? v.slice(0, 24) + '...' : v;
      print(`    ${colors.cyan}${k}${colors.reset} = ${preview}`);
    }
    print(`  ${colors.dim}(실제 값은 .env.local 참고)${colors.reset}`);
    print('');
    print(`${colors.bold}옵션 B) Vercel CLI 설치 후 자동 등록:${colors.reset}`);
    print('  npm i -g vercel && vercel login && npm run setup-secrets');
  }

  print('');
  print(`${colors.bold}${colors.yellow}==================================================${colors.reset}`);
  print(`${colors.bold}백엔드팀에 전달할 BACKEND_SHARED_SECRET (한 번만 표시됨):${colors.reset}`);
  print('');
  print(`  ${colors.cyan}${backendSecret}${colors.reset}`);
  print('');
  print(`  ${colors.dim}안전한 채널(Slack DM 등)로 백엔드팀에 전달하세요.${colors.reset}`);
  print(`  ${colors.dim}또한 BACKEND_REQUEST.md 파일을 백엔드팀에 공유하세요.${colors.reset}`);
  print(`${colors.bold}${colors.yellow}==================================================${colors.reset}`);

  print('');
  print(`${colors.green}완료. 다음 단계:${colors.reset}`);
  print('  1) (자동 등록 안했다면) Vercel 대시보드에 env 등록');
  print('  2) git push -> Vercel 자동 배포');
  print('  3) 위의 BACKEND_SHARED_SECRET을 백엔드팀에 공유');
  print('  4) 테스터에게 production 도메인 + 비밀번호 공유');
  print('');
  print(`${colors.dim}향후 비밀번호 회전: PASSWORD_ROTATION.md 참고${colors.reset}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
